namespace Application.CQRS.InventroyItemRequestWithdraw;

public record InventroyItemRequestWithdrawDetailsResponse
(
    int Id,
    bool IsActive,
    bool IsDeleted,
    int? ItemTypeFk,
    string? RequestNo,
    DateTime? RequestDate,
    string? DescriptionEn,
    string? DescriptionAr,
    bool? IsApproved,
    int? RequestedByFk,
    string? RequestedBy,
    int? AssignedToUserFk,
    int? ItemRequestStatusFk,
    string? WorkOrderNo,
    int? StoreFk,
    int? SentCount,
    bool? Axsynced,
    int? ProjectFk,
    int? Oufk,
    DateTime? ItemNeededDate,
    int? ScopeFk,
    int? CompanyFk,
    int? ServiceMainCategoryFk,
    bool? SiteManagerApproval,
    int? SiteManagerApprovalUserId,
    DateTime? SiteManagerApprovalDateTime,
    int? WarehouseManagerApprovalUserId,
    DateTime? WarehouseManagerApprovalDateTime,
    int? LocationFk,
    int? InventoryItemBudgetFk,
    int? SourceTypeId,
    int? EntityId,
    string? EntityFormula,
    int? ReceivedFk,
    int? VehicleFk,
    int? LineFk,
    string? SourceEntity,
    int? SourceId,
    int? SectorFk,
    int? CostCenterFk,
    int? CustomerFk,
    int? FactoryFk,
    int? FactoryLineFk
);