namespace Application.CQRS.Legacy.Sheet1;

public record Sheet1DetailsResponse
(
         string? RequestNo,
         double? RequestDate,
         string? Company,
         string? Project,
         string? Store,
         string? Scope,
         double? Vehicle,
         string? Line,
         double? WorkOrderNo,
         string? F10,
         string? F11,
         string? F12,
         string? F13,
         string? F14,
         string? F15,
         string? F16,
         string? F17,
         string? F18,
         string? F19,
         string? F20,
         string? F21,
         string? F22,
         string? F23,
         string? F24,
         string? F25,
         string? F26,
         string? F27,
         string? F28,
         string? F29,
         string? F30,
         string? F31,
         string? F32,
         string? F33,
         string? F34,
         string? F35,
         string? F36,
         string? F37,
         string? F38,
         string? F39,
         string? F40,
         string? F41,
         string? F42,
         string? F43
);
