// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111151532_alterSharhBookTable3")]
    partial class alterSharhBookTable3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Bab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BabIndex")
                        .HasColumnType("int");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Babs");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassificationIndex")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldCatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Narrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeathPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kamal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kunya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madhhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mawali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NarratedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nasab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relatives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifatAlSafwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirAlamAlNubala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Narrators");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.NarratorStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honorific")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kunya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lineage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NarratorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NarratorId");

                    b.ToTable("NarratorStudents");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.NarratorTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honorific")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kunya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lineage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NarratorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NarratorId");

                    b.ToTable("NarratorTeachers");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.NarratorsCriticism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriticName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriticStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NarratorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NarratorId");

                    b.ToTable("NarratorsCriticisms");
                });

            modelBuilder.Entity("Domain.Aggregates.BookSharhAggregate.SharhBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassificationRefrenaceId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SharhBooks");
                });

            modelBuilder.Entity("Domain.Aggregates.ClassificationAggregate.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutBook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BooksNumber")
                        .HasColumnType("int");

                    b.Property<string>("CatNameTakhreej")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullWriterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HadithCollectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StartId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WriterDeath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("HadithCollectionId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.Hadith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HId")
                        .HasColumnType("int");

                    b.Property<string>("HadithWithNoSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadithWithSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HavingMp3")
                        .HasColumnType("int");

                    b.Property<int>("HidOld")
                        .HasColumnType("int");

                    b.Property<string>("Hokm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Matn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewBabId")
                        .HasColumnType("int");

                    b.Property<int>("RawyId")
                        .HasColumnType("int");

                    b.Property<int?>("SelId")
                        .HasColumnType("int");

                    b.Property<string>("YusufTaraf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewBabId");

                    b.ToTable("Hadiths");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("MainMenuEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PartationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartationId");

                    b.ToTable("HadithCollections");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithLanguages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HadithLanguages");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithMissing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HId")
                        .HasColumnType("int");

                    b.Property<string>("HadithWithNoSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadithWithSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HavingMp3")
                        .HasColumnType("int");

                    b.Property<int>("HidOld")
                        .HasColumnType("int");

                    b.Property<string>("Hokm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewBabId")
                        .HasColumnType("int");

                    b.Property<int?>("OldBabId")
                        .HasColumnType("int");

                    b.Property<int?>("OldCatId")
                        .HasColumnType("int");

                    b.Property<int>("OldChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("OldHadithId")
                        .HasColumnType("int");

                    b.Property<int>("RawyId")
                        .HasColumnType("int");

                    b.Property<int>("SelId")
                        .HasColumnType("int");

                    b.Property<string>("YusufTaraf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HadithMissings");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithSharh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BabId")
                        .HasColumnType("int");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hid")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Selid")
                        .HasColumnType("int");

                    b.Property<string>("SharhWithNoSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharhWithSign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HadithSharhs");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithTranslations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hid")
                        .HasColumnType("int");

                    b.Property<string>("Hokm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Rawy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Selid")
                        .HasColumnType("int");

                    b.Property<string>("Sound")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("HadithTranslations");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithTranslationsMissing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hid")
                        .HasColumnType("int");

                    b.Property<string>("Hokm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Rawy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Selid")
                        .HasColumnType("int");

                    b.Property<string>("Sound")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HadithTranslationsMissings");
                });

            modelBuilder.Entity("Domain.Aggregates.TakhreejAggregate.HadithTakhreej", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BabName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hid")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Selid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HadithTakhreejs");
                });

            modelBuilder.Entity("Domain.Entities.MustafaTawfeeq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MustafaTawfeeqHadithID")
                        .HasColumnType("int");

                    b.Property<int>("all")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MustafaTawfeeqs");
                });

            modelBuilder.Entity("Domain.Entities.Partation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCollection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Partations");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Bab", b =>
                {
                    b.HasOne("Domain.Aggregates.BookAggregate.Book", "Book")
                        .WithMany("Babs")
                        .HasForeignKey("BookId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Book", b =>
                {
                    b.HasOne("Domain.Aggregates.ClassificationAggregate.Classification", "Classification")
                        .WithMany("Books")
                        .HasForeignKey("ClassificationId");

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.NarratorStudent", b =>
                {
                    b.HasOne("Domain.Aggregates.BookAggregate.Narrator", "Narrator")
                        .WithMany("NarratorStudents")
                        .HasForeignKey("NarratorId");

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.NarratorTeacher", b =>
                {
                    b.HasOne("Domain.Aggregates.BookAggregate.Narrator", "Narrator")
                        .WithMany("NarratorTeachers")
                        .HasForeignKey("NarratorId");

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.NarratorsCriticism", b =>
                {
                    b.HasOne("Domain.Aggregates.BookAggregate.Narrator", "Narrator")
                        .WithMany("NarratorsCriticisms")
                        .HasForeignKey("NarratorId");

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("Domain.Aggregates.ClassificationAggregate.Classification", b =>
                {
                    b.HasOne("Domain.Aggregates.HadithAggregate.HadithCollection", "HadithCollection")
                        .WithMany("Classifications")
                        .HasForeignKey("HadithCollectionId");

                    b.Navigation("HadithCollection");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.Hadith", b =>
                {
                    b.HasOne("Domain.Aggregates.BookAggregate.Bab", "Bab")
                        .WithMany("Hadiths")
                        .HasForeignKey("NewBabId");

                    b.Navigation("Bab");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithCollection", b =>
                {
                    b.HasOne("Domain.Entities.Partation", "Partation")
                        .WithMany("HadithCollections")
                        .HasForeignKey("PartationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partation");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithTranslations", b =>
                {
                    b.HasOne("Domain.Aggregates.HadithAggregate.HadithLanguages", "HadithLanguages")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HadithLanguages");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Bab", b =>
                {
                    b.Navigation("Hadiths");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Book", b =>
                {
                    b.Navigation("Babs");
                });

            modelBuilder.Entity("Domain.Aggregates.BookAggregate.Narrator", b =>
                {
                    b.Navigation("NarratorStudents");

                    b.Navigation("NarratorTeachers");

                    b.Navigation("NarratorsCriticisms");
                });

            modelBuilder.Entity("Domain.Aggregates.ClassificationAggregate.Classification", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Aggregates.HadithAggregate.HadithCollection", b =>
                {
                    b.Navigation("Classifications");
                });

            modelBuilder.Entity("Domain.Entities.Partation", b =>
                {
                    b.Navigation("HadithCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
